version: "3.9"

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports: 
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - flash-network

  redis:
      image: redis:8.4.0-alpine
      restart: always
      ports:
        - '6379:6379'
      volumes:
        - rcache:/data
      networks:
      - flash-network

  db:
    image: postgres:18.1-alpine
    container_name: postgres-flash-db
    environment:
        POSTGRES_USER: myuser
        POSTGRES_DB: flashdb
        POSTGRES_PASSWORD: supersecret
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data_18:/var/lib/postgresql_18/data
    networks:
      - flash-network
  
  products:
    container_name: flash-products
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
    restart: always
    ports:
      - '4500:4500'
    depends_on:
      - db
      - redis
      - broker
    environment:
      KAFKA_BROKER: broker:9092
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: supersecret
      DB_NAME: flashdb
      REDIS_URL: redis://redis:6379
    links:
      - db
      - redis
      - broker
    networks:
      - flash-network

volumes:
  rcache:
    driver: local
  postgres_data_18:
    driver: local     

networks:
  flash-network:
    driver: bridge

